In [41]:
print("Hello World!")

Hello World!

In [42]:
import requests
import pandas as pd
import defs

In [43]:
session = requests.Session()

In [44]:
instrument = "EUR_USD"
count = 10
granularity = "H1"

In [45]:
url = f"{defs.OANDA_URL}/instruments/{instrument}/candles"

In [46]:
url

'https://api-fxpractice.oanda.com/v3/instruments/EUR_USD/candles'

In [47]:
params = dict(
    count = count,
    granularity = granularity,
    price = "MBA"
)

In [48]:
params

{'count': 10, 'granularity': 'H1', 'price': 'MBA'}

In [49]:
response = session.get(url=url, params=params, headers=defs.SECURE_HEADER)

In [50]:
response.status_code

200

In [51]:
response.json()

{'instrument': 'EUR_USD',
 'granularity': 'H1',
 'candles': [{'complete': True,
   'volume': 5564,
   'time': '2026-05-01T11:00:00.000000000Z',
   'bid': {'o': '1.17441', 'h': '1.17575', 'l': '1.17432', 'c': '1.17506'},
   'mid': {'o': '1.17448', 'h': '1.17583', 'l': '1.17440', 'c': '1.17514'},
   'ask': {'o': '1.17456', 'h': '1.17591', 'l': '1.17448', 'c': '1.17522'}},
  {'complete': True,
   'volume': 9648,
   'time': '2026-05-01T12:00:00.000000000Z',
   'bid': {'o': '1.17505', 'h': '1.17680', 'l': '1.17475', 'c': '1.17567'},
   'mid': {'o': '1.17514', 'h': '1.17688', 'l': '1.17482', 'c': '1.17576'},
   'ask': {'o': '1.17523', 'h': '1.17697', 'l': '1.17490', 'c': '1.17584'}},
  {'complete': True,
   'volume': 11946,
   'time': '2026-05-01T13:00:00.000000000Z',
   'bid': {'o': '1.17567', 'h': '1.17630', 'l': '1.17432', 'c': '1.17609'},
   'mid': {'o': '1.17575', 'h': '1.17638', 'l': '1.17440', 'c': '1.17622'},
   'ask': {'o': '1.17583', 'h': '1.17647', 'l': '1.17448', 'c': '1.17634'}},
  {'complete': True,
   'volume': 15740,
   'time': '2026-05-01T14:00:00.000000000Z',
   'bid': {'o': '1.17609', 'h': '1.17845', 'l': '1.17596', 'c': '1.17667'},
   'mid': {'o': '1.17620', 'h': '1.17852', 'l': '1.17608', 'c': '1.17674'},
   'ask': {'o': '1.17632', 'h': '1.17861', 'l': '1.17620', 'c': '1.17682'}},
  {'complete': True,
   'volume': 11728,
   'time': '2026-05-01T15:00:00.000000000Z',
   'bid': {'o': '1.17667', 'h': '1.17701', 'l': '1.17523', 'c': '1.17543'},
   'mid': {'o': '1.17675', 'h': '1.17708', 'l': '1.17532', 'c': '1.17550'},
   'ask': {'o': '1.17683', 'h': '1.17716', 'l': '1.17542', 'c': '1.17558'}},
  {'complete': True,
   'volume': 8895,
   'time': '2026-05-01T16:00:00.000000000Z',
   'bid': {'o': '1.17542', 'h': '1.17564', 'l': '1.17369', 'c': '1.17374'},
   'mid': {'o': '1.17550', 'h': '1.17572', 'l': '1.17378', 'c': '1.17382'},
   'ask': {'o': '1.17558', 'h': '1.17581', 'l': '1.17386', 'c': '1.17390'}},
  {'complete': True,
   'volume': 5727,
   'time': '2026-05-01T17:00:00.000000000Z',
   'bid': {'o': '1.17374', 'h': '1.17397', 'l': '1.17285', 'c': '1.17322'},
   'mid': {'o': '1.17382', 'h': '1.17404', 'l': '1.17293', 'c': '1.17331'},
   'ask': {'o': '1.17391', 'h': '1.17413', 'l': '1.17300', 'c': '1.17340'}},
  {'complete': True,
   'volume': 7115,
   'time': '2026-05-01T18:00:00.000000000Z',
   'bid': {'o': '1.17324', 'h': '1.17333', 'l': '1.17188', 'c': '1.17265'},
   'mid': {'o': '1.17332', 'h': '1.17342', 'l': '1.17197', 'c': '1.17274'},
   'ask': {'o': '1.17340', 'h': '1.17350', 'l': '1.17206', 'c': '1.17282'}},
  {'complete': True,
   'volume': 3400,
   'time': '2026-05-01T19:00:00.000000000Z',
   'bid': {'o': '1.17266', 'h': '1.17276', 'l': '1.17171', 'c': '1.17189'},
   'mid': {'o': '1.17274', 'h': '1.17285', 'l': '1.17178', 'c': '1.17197'},
   'ask': {'o': '1.17282', 'h': '1.17294', 'l': '1.17185', 'c': '1.17205'}},
  {'complete': True,
   'volume': 3074,
   'time': '2026-05-01T20:00:00.000000000Z',
   'bid': {'o': '1.17188', 'h': '1.17217', 'l': '1.17146', 'c': '1.17198'},
   'mid': {'o': '1.17196', 'h': '1.17228', 'l': '1.17156', 'c': '1.17212'},
   'ask': {'o': '1.17205', 'h': '1.17252', 'l': '1.17164', 'c': '1.17227'}}]}

In [52]:
data = response.json()

In [53]:
data.keys()

dict_keys(['instrument', 'granularity', 'candles'])

In [54]:
len(data['candles'])

10

In [55]:
prices = ['mid', 'bid', 'ask']
ohlc = ['o', 'h', 'l', 'c']

In [56]:
for price in prices:
    for oh in ohlc:
        print(f"{price}_{oh}")

mid_o
mid_h
mid_l
mid_c
bid_o
bid_h
bid_l
bid_c
ask_o
ask_h
ask_l
ask_c

In [60]:
data['candles'][0]['bid']['o']

'1.17441'

In [62]:
our_data = []
for candle in data['candles']:
    if candle['complete'] == False:
        continue
    new_dict = {}
    new_dict['time'] = candle['time']
    new_dict['volume'] = candle['volume']
    for price in prices:
        for oh in ohlc:
            new_dict[f"{price}_{oh}"] = candle[price][oh]
    our_data.append(new_dict)

print(our_data[0])

{'time': '2026-05-01T11:00:00.000000000Z', 'volume': 5564, 'mid_o': '1.17448', 'mid_h': '1.17583', 'mid_l': '1.17440', 'mid_c': '1.17514', 'bid_o': '1.17441', 'bid_h': '1.17575', 'bid_l': '1.17432', 'bid_c': '1.17506', 'ask_o': '1.17456', 'ask_h': '1.17591', 'ask_l': '1.17448', 'ask_c': '1.17522'}

In [63]:
candles_df = pd.DataFrame.from_dict(our_data)

In [64]:
candles_df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2026-05-01T11:00:00.000000000Z,5564,1.17448,1.17583,1.17440,1.17514,1.17441,1.17575,1.17432,1.17506,1.17456,1.17591,1.17448,1.17522
1,2026-05-01T12:00:00.000000000Z,9648,1.17514,1.17688,1.17482,1.17576,1.17505,1.17680,1.17475,1.17567,1.17523,1.17697,1.17490,1.17584
2,2026-05-01T13:00:00.000000000Z,11946,1.17575,1.17638,1.17440,1.17622,1.17567,1.17630,1.17432,1.17609,1.17583,1.17647,1.17448,1.17634
3,2026-05-01T14:00:00.000000000Z,15740,1.17620,1.17852,1.17608,1.17674,1.17609,1.17845,1.17596,1.17667,1.17632,1.17861,1.17620,1.17682
4,2026-05-01T15:00:00.000000000Z,11728,1.17675,1.17708,1.17532,1.17550,1.17667,1.17701,1.17523,1.17543,1.17683,1.17716,1.17542,1.17558
5,2026-05-01T16:00:00.000000000Z,8895,1.17550,1.17572,1.17378,1.17382,1.17542,1.17564,1.17369,1.17374,1.17558,1.17581,1.17386,1.17390
6,2026-05-01T17:00:00.000000000Z,5727,1.17382,1.17404,1.17293,1.17331,1.17374,1.17397,1.17285,1.17322,1.17391,1.17413,1.17300,1.17340
7,2026-05-01T18:00:00.000000000Z,7115,1.17332,1.17342,1.17197,1.17274,1.17324,1.17333,1.17188,1.17265,1.17340,1.17350,1.17206,1.17282
8,2026-05-01T19:00:00.000000000Z,3400,1.17274,1.17285,1.17178,1.17197,1.17266,1.17276,1.17171,1.17189,1.17282,1.17294,1.17185,1.17205
9,2026-05-01T20:00:00.000000000Z,3074,1.17196,1.17228,1.17156,1.17212,1.17188,1.17217,1.17146,1.17198,1.17205,1.17252,1.17164,1.17227

In [65]:
candles_df.to_pickle("EUR_USD_H1.pkl")

In [67]:
test_df = pd.read_pickle("EUR_USD_H1.pkl")

In [68]:
test_df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2026-05-01T11:00:00.000000000Z,5564,1.17448,1.17583,1.17440,1.17514,1.17441,1.17575,1.17432,1.17506,1.17456,1.17591,1.17448,1.17522
1,2026-05-01T12:00:00.000000000Z,9648,1.17514,1.17688,1.17482,1.17576,1.17505,1.17680,1.17475,1.17567,1.17523,1.17697,1.17490,1.17584
2,2026-05-01T13:00:00.000000000Z,11946,1.17575,1.17638,1.17440,1.17622,1.17567,1.17630,1.17432,1.17609,1.17583,1.17647,1.17448,1.17634
3,2026-05-01T14:00:00.000000000Z,15740,1.17620,1.17852,1.17608,1.17674,1.17609,1.17845,1.17596,1.17667,1.17632,1.17861,1.17620,1.17682
4,2026-05-01T15:00:00.000000000Z,11728,1.17675,1.17708,1.17532,1.17550,1.17667,1.17701,1.17523,1.17543,1.17683,1.17716,1.17542,1.17558
5,2026-05-01T16:00:00.000000000Z,8895,1.17550,1.17572,1.17378,1.17382,1.17542,1.17564,1.17369,1.17374,1.17558,1.17581,1.17386,1.17390
6,2026-05-01T17:00:00.000000000Z,5727,1.17382,1.17404,1.17293,1.17331,1.17374,1.17397,1.17285,1.17322,1.17391,1.17413,1.17300,1.17340
7,2026-05-01T18:00:00.000000000Z,7115,1.17332,1.17342,1.17197,1.17274,1.17324,1.17333,1.17188,1.17265,1.17340,1.17350,1.17206,1.17282
8,2026-05-01T19:00:00.000000000Z,3400,1.17274,1.17285,1.17178,1.17197,1.17266,1.17276,1.17171,1.17189,1.17282,1.17294,1.17185,1.17205
9,2026-05-01T20:00:00.000000000Z,3074,1.17196,1.17228,1.17156,1.17212,1.17188,1.17217,1.17146,1.17198,1.17205,1.17252,1.17164,1.17227